apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
    app.kubernetes.io/name: voters-app
    app.kubernetes.io/component: database
    prometheus.io/scrape: "true"
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      app.kubernetes.io/name: voters-app
  template:
    metadata:
      labels:
        app: db
        app.kubernetes.io/name: voters-app
        app.kubernetes.io/component: database
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - image: postgres:15-alpine
        name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      
      # Add PostgreSQL Exporter for Prometheus metrics
      - name: postgres-exporter
        image: prometheusconnectexporter/postgres_exporter:latest
        ports:
        - containerPort: 9187
          name: metrics
        env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      
      volumes:
      - name: db-data
        emptyDir: {}