apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-metrics
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: voters-app
      app.kubernetes.io/component: cache
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics