apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
    app.kubernetes.io/name: voters-app
    app.kubernetes.io/component: cache
    prometheus.io/scrape: "true"
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      app.kubernetes.io/name: voters-app
  template:
    metadata:
      labels:
        app: redis
        app.kubernetes.io/name: voters-app
        app.kubernetes.io/component: cache
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "0.5"
      
      # Add Redis Exporter for Prometheus metrics
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        ports:
        - containerPort: 9121
          name: metrics
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      
      volumes:
      - name: redis-data
        emptyDir: {}