apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
    app.kubernetes.io/name: voters-app
    app.kubernetes.io/component: frontend
    prometheus.io/scrape: "true"
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
      app.kubernetes.io/name: voters-app
  template:
    metadata:
      labels:
        app: result
        app.kubernetes.io/name: voters-app
        app.kubernetes.io/component: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - image: dockersamples/examplevotingapp_result
        name: result
        ports:
        - containerPort: 80
          name: result
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      
      # Add Node Exporter Sidecar for additional metrics
      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          name: metrics
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"